name       : python-pywavelets
version    : 0.5.2
release    : 4
source     :
    - https://github.com/PyWavelets/pywt/archive/v0.5.2.tar.gz : e36d629f40f7781da2dcaa2139bc476e9deaf91d79f675b5ce0bde6e775d1b53
homepage   : https://github.com/PyWavelets/pywt
license    : MIT
component  : programming.python
summary    : Wavelet Transforms in Python
description: |
    PyWavelets is a free Open Source library for wavelet transforms in Python.
builddeps  :
    - cython
    - matplotlib
    - numpy
    - python-nose
    - python-pytest
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
